# Form implementation generated from reading ui file 'dlgCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgCalendar(object):
    def setupUi(self, dlgCalendar):
        dlgCalendar.setObjectName("dlgCalendar")
        dlgCalendar.resize(240, 175)
        dlgCalendar.setMinimumSize(QtCore.QSize(240, 175))
        dlgCalendar.setMaximumSize(QtCore.QSize(240, 175))
        self.centralwidget = QtWidgets.QWidget(dlgCalendar)
        self.centralwidget.setObjectName("centralwidget")
        self.Calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.Calendar.setGeometry(QtCore.QRect(0, 0, 240, 170))
        self.Calendar.setMinimumSize(QtCore.QSize(240, 170))
        self.Calendar.setMaximumSize(QtCore.QSize(240, 170))
        self.Calendar.setObjectName("Calendar")
        dlgCalendar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(dlgCalendar)
        self.statusbar.setObjectName("statusbar")
        dlgCalendar.setStatusBar(self.statusbar)

        self.retranslateUi(dlgCalendar)
        QtCore.QMetaObject.connectSlotsByName(dlgCalendar)

    def retranslateUi(self, dlgCalendar):
        _translate = QtCore.QCoreApplication.translate
        dlgCalendar.setWindowTitle(_translate("dlgCalendar", "Calendario"))
