# Form implementation generated from reading ui file 'dlgDatos.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgDatos(object):
    def setupUi(self, dlgDatos):
        dlgDatos.setObjectName("dlgDatos")
        dlgDatos.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        dlgDatos.resize(400, 300)
        self.btnAceptar = QtWidgets.QPushButton(dlgDatos)
        self.btnAceptar.setGeometry(QtCore.QRect(170, 220, 75, 23))
        self.btnAceptar.setObjectName("btnAceptar")
        self.label = QtWidgets.QLabel(dlgDatos)
        self.label.setGeometry(QtCore.QRect(90, 130, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(dlgDatos)
        self.checkBox.setGeometry(QtCore.QRect(100, 180, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(dlgDatos)
        self.checkBox_2.setGeometry(QtCore.QRect(230, 180, 70, 17))
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_2 = QtWidgets.QLabel(dlgDatos)
        self.label_2.setGeometry(QtCore.QRect(150, 20, 111, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/interrogante.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(dlgDatos)
        QtCore.QMetaObject.connectSlotsByName(dlgDatos)

    def retranslateUi(self, dlgDatos):
        _translate = QtCore.QCoreApplication.translate
        dlgDatos.setWindowTitle(_translate("dlgDatos", "Dialog"))
        self.btnAceptar.setText(_translate("dlgDatos", "Aceptar"))
        self.label.setText(_translate("dlgDatos", "Elija los datos que desea exportar"))
        self.checkBox.setText(_translate("dlgDatos", "Clientes"))
        self.checkBox_2.setText(_translate("dlgDatos", "Coches"))
