# Form implementation generated from reading ui file 'dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(270, 220)
        dlgSalir.setMinimumSize(QtCore.QSize(270, 220))
        dlgSalir.setMaximumSize(QtCore.QSize(270, 220))
        dlgSalir.setModal(True)
        self.lblSalir = QtWidgets.QLabel(dlgSalir)
        self.lblSalir.setGeometry(QtCore.QRect(20, 110, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lblSalir.setFont(font)
        self.lblSalir.setObjectName("lblSalir")
        self.lblImgsalir = QtWidgets.QLabel(dlgSalir)
        self.lblImgsalir.setGeometry(QtCore.QRect(90, 20, 90, 70))
        self.lblImgsalir.setMinimumSize(QtCore.QSize(90, 70))
        self.lblImgsalir.setMaximumSize(QtCore.QSize(90, 70))
        self.lblImgsalir.setText("")
        self.lblImgsalir.setPixmap(QtGui.QPixmap("img/advertencia.png"))
        self.lblImgsalir.setScaledContents(True)
        self.lblImgsalir.setObjectName("lblImgsalir")
        self.btnsalir = QtWidgets.QPushButton(dlgSalir)
        self.btnsalir.setGeometry(QtCore.QRect(50, 140, 70, 20))
        self.btnsalir.setMinimumSize(QtCore.QSize(70, 20))
        self.btnsalir.setMaximumSize(QtCore.QSize(70, 20))
        self.btnsalir.setObjectName("btnsalir")
        self.btnCancelar = QtWidgets.QPushButton(dlgSalir)
        self.btnCancelar.setGeometry(QtCore.QRect(150, 140, 70, 20))
        self.btnCancelar.setMinimumSize(QtCore.QSize(70, 20))
        self.btnCancelar.setMaximumSize(QtCore.QSize(70, 20))
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Aviso"))
        self.lblSalir.setText(_translate("dlgSalir", "Esta seguro que desea salir de la aplicacion?"))
        self.btnsalir.setText(_translate("dlgSalir", "Salir"))
        self.btnCancelar.setText(_translate("dlgSalir", "Cancelar"))
