# Form implementation generated from reading ui file 'dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(270, 220)
        dlgSalir.setMinimumSize(QtCore.QSize(270, 220))
        dlgSalir.setMaximumSize(QtCore.QSize(270, 220))
        self.lblSalir = QtWidgets.QLabel(dlgSalir)
        self.lblSalir.setGeometry(QtCore.QRect(20, 110, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.lblSalir.setFont(font)
        self.lblSalir.setObjectName("lblSalir")
        self.lblImagenSalir = QtWidgets.QLabel(dlgSalir)
        self.lblImagenSalir.setGeometry(QtCore.QRect(90, 10, 100, 100))
        self.lblImagenSalir.setMinimumSize(QtCore.QSize(100, 100))
        self.lblImagenSalir.setMaximumSize(QtCore.QSize(100, 100))
        self.lblImagenSalir.setText("")
        self.lblImagenSalir.setPixmap(QtGui.QPixmap("img/advertencia.png"))
        self.lblImagenSalir.setScaledContents(True)
        self.lblImagenSalir.setObjectName("lblImagenSalir")
        self.btnSalir = QtWidgets.QPushButton(dlgSalir)
        self.btnSalir.setGeometry(QtCore.QRect(60, 170, 70, 20))
        self.btnSalir.setMinimumSize(QtCore.QSize(70, 20))
        self.btnSalir.setMaximumSize(QtCore.QSize(70, 20))
        self.btnSalir.setObjectName("btnSalir")
        self.btnCancelar = QtWidgets.QPushButton(dlgSalir)
        self.btnCancelar.setGeometry(QtCore.QRect(160, 170, 70, 20))
        self.btnCancelar.setMinimumSize(QtCore.QSize(70, 20))
        self.btnCancelar.setMaximumSize(QtCore.QSize(70, 20))
        self.btnCancelar.setObjectName("btnCancelar")

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Aviso"))
        self.lblSalir.setText(_translate("dlgSalir", "Estas seguro que desa salir de la aplicacion"))
        self.btnSalir.setText(_translate("dlgSalir", "Salir"))
        self.btnCancelar.setText(_translate("dlgSalir", "Cancelar"))
