# Form implementation generated from reading ui file 'ventMain.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventMain(object):
    def setupUi(self, ventMain):
        ventMain.setObjectName("ventMain")
        ventMain.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ventMain)
        self.centralwidget.setObjectName("centralwidget")
        self.BtnStart = QtWidgets.QPushButton(self.centralwidget)
        self.BtnStart.setGeometry(QtCore.QRect(280, 392, 131, 41))
        self.BtnStart.setObjectName("BtnStart")
        ventMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ventMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ventMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ventMain)
        self.statusbar.setObjectName("statusbar")
        ventMain.setStatusBar(self.statusbar)

        self.retranslateUi(ventMain)
        QtCore.QMetaObject.connectSlotsByName(ventMain)

    def retranslateUi(self, ventMain):
        _translate = QtCore.QCoreApplication.translate
        ventMain.setWindowTitle(_translate("ventMain", "Talleres Teis"))
        self.BtnStart.setText(_translate("ventMain", "Button"))
