# Form implementation generated from reading ui file 'ventCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_venCalendaraula(object):
    def setupUi(self, venCalendaraula):
        venCalendaraula.setObjectName("venCalendaraula")
        venCalendaraula.resize(240, 175)
        venCalendaraula.setMinimumSize(QtCore.QSize(240, 175))
        venCalendaraula.setMaximumSize(QtCore.QSize(240, 175))
        self.centralwidget = QtWidgets.QWidget(venCalendaraula)
        self.centralwidget.setObjectName("centralwidget")
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 240, 170))
        self.calendar.setMinimumSize(QtCore.QSize(240, 170))
        self.calendar.setMaximumSize(QtCore.QSize(240, 170))
        self.calendar.setObjectName("calendar")
        venCalendaraula.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(venCalendaraula)
        self.statusbar.setObjectName("statusbar")
        venCalendaraula.setStatusBar(self.statusbar)

        self.retranslateUi(venCalendaraula)
        QtCore.QMetaObject.connectSlotsByName(venCalendaraula)

    def retranslateUi(self, venCalendaraula):
        _translate = QtCore.QCoreApplication.translate
        venCalendaraula.setWindowTitle(_translate("venCalendaraula", "Calendario"))
