# Generated by Django 4.1.2 on 2022-12-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodcuto', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=75)),
                ('precio', models.IntegerField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
