# Generated by Django 4.1.2 on 2022-12-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0002_productos_alter_cliente_dni_alter_cliente_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
