# Generated by Django 4.1.2 on 2022-12-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0003_alter_productos_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='prodcuto',
            new_name='producto',
        ),
    ]
