# Generated by Django 4.1.7 on 2023-02-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0004_rename_prodcuto_productos_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='clientes'),
        ),
    ]
