# Generated by Django 4.1.7 on 2023-02-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0005_cliente_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='imagen',
        ),
    ]
