# Form implementation generated from reading ui file 'C:/Users/a21martinqr/Documents/GitHub/Desenvolvemento-de-Interfaces/QuintanaRana/dlgDatos.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgDatos(object):
    def setupUi(self, dlgDatos):
        dlgDatos.setObjectName("dlgDatos")
        dlgDatos.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        dlgDatos.resize(400, 300)
        dlgDatos.setMinimumSize(QtCore.QSize(400, 300))
        dlgDatos.setMaximumSize(QtCore.QSize(400, 300))
        dlgDatos.setModal(True)
        self.label = QtWidgets.QLabel(dlgDatos)
        self.label.setGeometry(QtCore.QRect(70, 130, 271, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.label.setStyleSheet("color: rgb(81, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(dlgDatos)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 81, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/a21martinqr/Documents/GitHub/Desenvolvemento-de-Interfaces/QuintanaRana\\img/pregunta.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.chkClientes = QtWidgets.QCheckBox(dlgDatos)
        self.chkClientes.setGeometry(QtCore.QRect(130, 170, 70, 17))
        self.chkClientes.setObjectName("chkClientes")
        self.chkCoches = QtWidgets.QCheckBox(dlgDatos)
        self.chkCoches.setGeometry(QtCore.QRect(220, 170, 70, 17))
        self.chkCoches.setObjectName("chkCoches")
        self.btnExportaDatos = QtWidgets.QPushButton(dlgDatos)
        self.btnExportaDatos.setGeometry(QtCore.QRect(160, 210, 75, 23))
        self.btnExportaDatos.setObjectName("btnExportaDatos")

        self.retranslateUi(dlgDatos)
        QtCore.QMetaObject.connectSlotsByName(dlgDatos)

    def retranslateUi(self, dlgDatos):
        _translate = QtCore.QCoreApplication.translate
        dlgDatos.setWindowTitle(_translate("dlgDatos", "Exportar Datos"))
        self.label.setText(_translate("dlgDatos", "Elija los datos que desea exportar:"))
        self.chkClientes.setText(_translate("dlgDatos", "Clientes"))
        self.chkCoches.setText(_translate("dlgDatos", "Coches"))
        self.btnExportaDatos.setText(_translate("dlgDatos", "Aceptar"))
